### ISSUE TITLE
Screenshot taken too early

### ISSUE THREAD

**Issue by Nowakowa** [NovusPL/_Personal#10]
![20180821-115955](https://user-images.githubusercontent.com/42573203/44397027-0af2b100-a53f-11e8-93a3-2b855ee603c5.png)
![20180821-121955](https://user-images.githubusercontent.com/42573203/44397028-0af2b100-a53f-11e8-979a-e3191092fcf1.png)

happened 3 times out of 48 pictures ~6.25%

**Comment by NovusPL** [comment]
need to redefine Wait callbacks in code.

instead of time.sleep() use : 
http://selenium-python.readthedocs.io/waits.html

**Comment by NovusPL** [comment]
resolved  by updating wait callbacks
